### ISSUE TITLE
Enable Basic Login

### ISSUE THREAD

**Issue by nikolainobadi** [nikolainobadi/SpeedStreak#1]
I've added NoCredentialLoginView in the UI folder.
 - added a single button to 'log in' to the app.
 - add a temporary view (call it whatever you like, but TempInAppView would suffice)
 - modify the body in LaunchCoordinatorView to display NoCredentialLoginView is the user is logged out, and the new view if the user is logged in.

NOTE: - we're not going to end up using these views, but it will be good practice to learn separation of concerns. Don't worry about doing it 'right' for now, just do what feels right haha

**Comment by Jdatle** [comment]
COMPLETED.
NOTES:
1st attempt was to make the button's action call out a function. The function would then have the logic to determine which view to navigate to next. But I couldn't get it to change views.
2nd attempt works, but view is now coupled with the logic.
